import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import { requireHouseholdContext } from "@/lib/session-helpers";
import { assertCanAccessOwnRecord } from "@/lib/authz";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CONTRACT_STATUS_LABEL, PAYMENT_STATUS_LABEL } from "@/lib/constants";
import { summarizeBalance } from "@/services/leave-service";

export const metadata: Metadata = { title: "Contract — SevaSetu" };

export default async function HouseholdContractDetailPage({
  params,
}: PageProps<"/household/contracts/[id]">) {
  const { session } = await requireHouseholdContext();
  const { id } = await params;

  const contract = await prisma.employmentContract.findUnique({
    where: { id },
    include: {
      helper: { include: { user: true } },
      household: true,
      serviceCategory: true,
      salaryCalculation: true,
      leaveBalance: true,
      payments: { orderBy: { periodYear: "desc" } },
      attendanceRecords: { orderBy: { date: "desc" }, take: 10 },
    },
  });

  if (!contract) notFound();
  assertCanAccessOwnRecord(session, contract.household.userId);

  const schedule = contract.workSchedule as { days: string[]; startTime: string; endTime: string };
  const leaveSummary = contract.leaveBalance ? summarizeBalance(contract.leaveBalance) : null;

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="font-serif text-2xl font-semibold">
            Employment agreement — {contract.helper.user.name}
          </h1>
          <p className="text-sm text-muted-foreground">{contract.serviceCategory.name}</p>
        </div>
        <Badge variant={contract.status === "ACTIVE" ? "success" : "outline"}>
          {CONTRACT_STATUS_LABEL[contract.status]}
        </Badge>
      </div>

      <Card>
        <CardHeader><CardTitle>Terms</CardTitle></CardHeader>
        <CardContent className="space-y-3 text-sm">
          <p><span className="font-medium">Start date:</span> {contract.startDate.toLocaleDateString("en-IN")}</p>
          <p><span className="font-medium">Schedule:</span> {schedule.days?.join(", ")}, {schedule.startTime}–{schedule.endTime}</p>
          <div>
            <p className="font-medium">Responsibilities</p>
            <ul className="ml-5 list-disc text-muted-foreground">
              {contract.responsibilities.map((r) => <li key={r}>{r}</li>)}
            </ul>
          </div>
          <p className="text-xs text-muted-foreground">
            This is a structured digital agreement generated by SevaSetu for record-keeping and
            transparency. It is not a substitute for professional legal advice — see{" "}
            <Link href="/legal" className="underline">legal &amp; compliance notes</Link>.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle>Salary breakdown (locked at agreement time)</CardTitle></CardHeader>
        <CardContent className="space-y-1 text-sm">
          <Row label="Base worker salary" value={Number(contract.salaryCalculation.baseSalary)} />
          <Row label="Skill tier adjustment" value={Number(contract.salaryCalculation.skillAdjustment)} />
          <Row label="Scope of work adjustment" value={Number(contract.salaryCalculation.scopeAdjustment)} />
          <Row label="Worker salary" value={Number(contract.salaryCalculation.workerSalary)} bold />
          <Row label="SevaSetu platform fee" value={Number(contract.salaryCalculation.platformFee)} />
          <Row label="Total monthly payment" value={Number(contract.salaryCalculation.totalPayment)} bold large />
        </CardContent>
      </Card>

      {leaveSummary && (
        <Card>
          <CardHeader><CardTitle>Leave balance</CardTitle></CardHeader>
          <CardContent className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
            <Stat label="Annual leave remaining" value={`${leaveSummary.annualRemaining}/${leaveSummary.annualTotal}`} />
            <Stat label="Sick leave remaining" value={`${leaveSummary.sickRemaining}/${leaveSummary.sickTotal}`} />
            <Stat label="Unpaid leave taken" value={`${leaveSummary.unpaidUsed} day(s)`} />
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>Recent payments</CardTitle>
          <Button asChild size="sm" variant="ghost"><Link href="/household/payments">View all</Link></Button>
        </CardHeader>
        <CardContent>
          <div className="divide-y divide-border">
            {contract.payments.slice(0, 4).map((p) => (
              <div key={p.id} className="flex items-center justify-between py-2 text-sm">
                <span>{p.periodMonth}/{p.periodYear}</span>
                <span>₹{Number(p.totalAmount).toLocaleString("en-IN")}</span>
                <Badge variant={p.status === "PAID" ? "success" : "warning"}>
                  {PAYMENT_STATUS_LABEL[p.status]}
                </Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>Recent attendance</CardTitle>
          <Button asChild size="sm" variant="ghost"><Link href="/household/attendance">Mark attendance</Link></Button>
        </CardHeader>
        <CardContent>
          <div className="divide-y divide-border">
            {contract.attendanceRecords.map((a) => (
              <div key={a.id} className="flex items-center justify-between py-2 text-sm">
                <span>{a.date.toLocaleDateString("en-IN")}</span>
                <Badge variant={a.status === "PRESENT" ? "success" : a.status === "ABSENT" ? "destructive" : "outline"}>
                  {a.status}
                </Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="flex flex-wrap gap-3">
        <Button asChild variant="outline"><Link href={`/household/replacement?contractId=${contract.id}`}>Request replacement</Link></Button>
        <Button asChild variant="outline"><Link href={`/household/grievances?contractId=${contract.id}`}>Raise a grievance</Link></Button>
      </div>
    </div>
  );
}

function Row({ label, value, bold, large }: { label: string; value: number; bold?: boolean; large?: boolean }) {
  return (
    <div className={`flex items-center justify-between py-1 ${bold ? "font-medium" : ""} ${large ? "text-lg" : ""}`}>
      <span>{label}</span>
      <span>₹{value.toLocaleString("en-IN")}</span>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-lg font-semibold">{value}</p>
      <p className="text-muted-foreground">{label}</p>
    </div>
  );
}
